language: node_js

node_js:
  - "node"

cache: npm

install:
  - npm install

script:
  - npm run build

branches:
  only:
  - master

deploy:
  provider: surge
  project: ./dist/
  domain: petroivankiv.surge.sh